tools:
  - class_name: "AIME.tools.remote_code_interpreter.RemoteCodeInterpreter"
    config: 
      # Remote service configuration
      service_url: "http://localhost:8001"  # Remote service address
      timeout: 10  # Request timeout (seconds)
      max_retries: 3  # Maximum retry count
      retry_delay: 1.0  # Retry delay (seconds)
      session_timeout: 1800  # Session timeout (seconds)
      reuse_sessions: true  # Whether to reuse sessions
    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "Submit and execute a piece of Python code to a persistent remote Jupyter Notebook session. The session retains all previously executed code states (such as variables and functions) for subsequent calls. This function is only for code execution and will return the textual or image output generated in the Notebook. Note: The execution environment is non-interactive, does not support functions requiring real-time user input (such as `input()`), and has restricted access to the file system and network."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The Python code string to be submitted and executed in the remote Jupyter Notebook."