tools:
  - class_name: "AIME.tools.remote_code_interpreter.RemoteCodeInterpreter"
    config: 
      # 远程服务配置
      service_url: "http://localhost:8001"  # 远程服务地址
      timeout: 15  # 请求超时时间（秒）
      max_retries: 5  # 最大重试次数
      retry_delay: 1.0  # 重试延迟时间（秒）
      session_timeout: 1800  # 会话超时时间（秒）
      reuse_sessions: true  # 是否复用会话
      type: native
    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "Submit and execute a piece of Python code to a persistent remote Jupyter Notebook session. The session retains all previously executed code states (such as variables and functions) for subsequent calls. This function is only for code execution and will return the textual or image output generated in the Notebook. Note: The execution environment is non-interactive, does not support functions requiring real-time user input (such as `input()`), and has restricted access to the file system and network."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The Python code string to be submitted and executed in the remote Jupyter Notebook."
          required: ["code"]